### PR TITLE
fix: Reenabling E2E test

### LINKED ISSUE #866: [ADO Extension] E2E tests
E2E tests were disabled in #844 due to an [issue in webpack](https://github.com/microsoft/azure-pipelines-task-lib/issues/794). When it is resolved, the tests will need to be turned back on.

### PR DESCRIPTION
**Pull request by ThanyaLeif**
#### Details

This PR reenables E2E test after azure-pipelines-task-lib latest release.

##### Motivation
Add an extra layer of security to ensure future code changes don't break the Extension

##### Context
Since E2E tests were disabled a year ago when the Extension was in an early stage of development, it was necessary some workarounds that include:

* Switching from Mocha to Jest as a test framework
* Refactoring of the `run.ts` class, now `run-simple-inputs.js`, responsible for setting the environment for the E2E tests.
* Updating `azure-pipeline-task-lib` to v4.0.1-preview that has a fix for a problem found in [#794](https://github.com/microsoft/azure-pipelines-task-lib/issues/794https://github.com/microsoft/azure-pipelines-task-lib/issues/794)  
* Creating a local mock-test file to work around Node issues seen in the pipeline.
* Updating the GitHub workflow to run e2e tests on PR.

These changes will affect ADO extension's side exclusively.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #866 
- [x] Added relevant unit test for your changes. (`yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] Described how this PR impacts both the ADO extension and the GitHub action

### CODE REVIEW

File: packages/ado-extension/e2e/run-simple-inputs.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    fs.mkdirSync(tempPath);
+}
+process.env['AGENT_TEMPDIRECTORY'] = tempPath;
+
+// Run the task:
+const taskExecutablePath = path.join(__dirname, '..', 'dist', 'pkg', 'index.js');
+const tmr = new tmrm.TaskMockRunner(taskExecutablePath);
+
+for (const name of Object.keys(inputs)) {
+    console.log(`e2e tests is apply up input ${name} to value ${inputs[name]}`);
```
Comment (katydecorah) [inline packages/ado-extension/e2e/run-simple-inputs.js:35]:
```suggestion
    console.log(`e2e tests is applying input ${name} to value ${inputs[name]}`);
```

**Review by brocktaylor7 — APPROVED** [review]
