### PR TITLE
fix(ado-extension): failure counts in PR comment

### LINKED ISSUE #945: [ADO extension] Inconsistent/incorrect failure instance counts in PR comments
(Discovered during release validation)

Failure instance counts don't show as expected in ADO PR comments
* They should show only a list of new failures when there is a baseline file that contains some of the failures found during a scan
* When there is no baseline file, the total failure instance count shows the number of failure groups (i.e. when opening a report, this is the number of cards) instead of the total number of instances for each rule (if a given card in the report has x URLs listed, it should count x failure instances for that card, not 1 failure instance for only the card).

### PR DESCRIPTION
**Pull request by lisli1**
#### Details

Fixes the failure counts showing in the ADO PR comments. There was some refactoring done as well in result-markdown-builder.ts and its corresponding test file.

##### Motivation

Addresses #945 

##### Context
PR comment screenshots:
1. Baseline file configured, no baseline file added to repo
image
2. Generated baseline file from (1) added to the repo, with previous comment below it as a child comment
image
3. Baseline file with fewer failure instances than found in current scan (scenario where errors were introduced)
image
4. Baseline file with more failure instances than found in current scan (assume errors were fixed)
image
5. Removed baselineFile input from yml (baseline not configured)
image

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #945
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] (after PR created) The `Accessibility Checks (pull_request)` check should fail. All other checks should pass.

### CODE REVIEW

File: packages/shared/src/mark-down/result-markdown-builder.ts [hunk 1]
```diff
@@ -164,45 +165,25 @@ export class ResultMarkdownBuilder {
...
-                const failureCount = failuresGroup.failed.length;
-                const ruleId = failuresGroup.failed[0].rule.ruleId;
-                const ruleDescription = failuresGroup.failed[0].rule.description;
-                return [this.failedRuleListItemBaseline(failureCount, ruleId, ruleDescription), sectionSeparator()].join('');
-            });
-            let failureInstancesHeading = `${failedChecks} failure instances`;
-            if (baselineEvaluation !== undefined && baselineEvaluation.totalBaselineViolations > 0) {
+            let failedRulesList;
+            let failureInstances = totalFailureInstances;
+            if (!baselineInfo.baselineEvaluation) {
```
Comment (DaveTryon) [inline packages/shared/src/mark-down/result-markdown-builder.ts:179]: When there's an else, most people find it more intuitive to have the positive case first--having the negative case requires a little extra effort for mental parsing

**Review by DaveTryon — APPROVED** [review]
